apiVersion: apps/v1
kind: Deployment
metadata:
  name: labels
  labels:
    app: labels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labels
  template:
    metadata:
      labels:
        app: labels
    spec:
      containers:
      - name: labels
        image: minio/minio:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: labels-svc
spec:
  selector:
    app: labels
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP